
export const CREATE_TENANT = 'CREATE_TENANT'
export const UPDATE_TENANT = 'UPDATE_TENANT'
export const DELETE_TENANT = 'DELETE_TENANT'
export const FETCH_TENANTS = 'FETCH_TENANTS'
export const FETCH_ONE = 'FETCH_ONE'

export const CREATE_LANDLORD = 'CREATE_LANDLORD'
export const UPDATE_LANDLORD = 'UPDATE_LANDLORD'
export const DELETE_LANDLORD = 'DELETE_LANDLORD'
export const FETCH_LANDLORDS = 'FETCH_LANDLORDS'
export const FETCH_LANDLORD = 'FETCH_LANDLORD'

export const START_LOADING = 'START_LOADING'
export const FINISH_LOADING = 'FINISH_LOADING'
